apiVersion: v1
kind: Service
metadata:
  name: {{ include "cv-api.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cv-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cv-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http