name: 'Setup Java & Maven'
description: 'Sets up Java 21 with Temurin distribution and activates Maven dependency cache'

inputs:
  java-version:
    description: 'Java version to install'
    required: false
    default: '21'

runs:
  using: 'composite'

  steps:
    - name: 'Set up Java ${{ inputs.java-version }}'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'

    - name: 'Verify toolchain'
      shell: bash
      run: |
        echo "Java version:"; java -version
        echo "Maven version:"; mvn -version
